name: CI-CPU
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  build:
    name: Build / ${{ matrix.os }} / Python ${{ matrix.major }}.${{ matrix.minor }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
        major: [3]
        minor: [9, 10]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Test
      run: pytest test/unit/test_hyray.py
