name: CI-CPU
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  build:
    name: Build / ${{ matrix.os }} / Python ${{ matrix.major }}.${{ matrix.minor }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
        python-version: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        python3 -m pip install --upgrade pip
        pip install -e .[test]

    - name: Test
      run: pytest test/unit/test_hyray.py
